In [64]:
# Create and Array

from array import *

In [65]:
# array of integers
int_array = array('i', [1,2,3,4])
int_array

array('i', [1, 2, 3, 4])

In [66]:
# array of floats
float_array = array('d', [1.3, 4.5, 5.7])
float_array

array('d', [1.3, 4.5, 5.7])

In [67]:
# replace

int_array[1] = 100
int_array

array('i', [1, 100, 3, 4])

In [68]:
# insert

int_array.insert(0, 200)
int_array

array('i', [200, 1, 100, 3, 4])

In [69]:
# Travers

for i in int_array:
    print(i)

200
1
100
3
4


In [70]:
# delete

int_array.remove(100)
int_array

array('i', [200, 1, 3, 4])

In [71]:
int_array.append(3000)
int_array

array('i', [200, 1, 3, 4, 3000])

In [72]:
ext = array('i', [4000, 5000, 6000])
int_array.extend(ext)
int_array

array('i', [200, 1, 3, 4, 3000, 4000, 5000, 6000])

In [73]:
ext2 = [22, 33, 44]
int_array.fromlist(ext2)
int_array

array('i', [200, 1, 3, 4, 3000, 4000, 5000, 6000, 22, 33, 44])

In [74]:
int_array.pop()

44

In [75]:
int_array

array('i', [200, 1, 3, 4, 3000, 4000, 5000, 6000, 22, 33])

In [76]:
int_array.index(3000)

4

In [77]:
int_array.reverse()
int_array

array('i', [33, 22, 6000, 5000, 4000, 3000, 4, 3, 1, 200])

In [78]:
int_array[1:4]

array('i', [22, 6000, 5000])

In [79]:
import numpy as np

two_dim_array = np.array([[1,2,3], [4,5,6], [10,20,90]])
two_dim_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 90]])

In [80]:
two_dim_array = np.insert(two_dim_array, 0, [-1, -2, -2], 0)
two_dim_array

array([[-1, -2, -2],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 90]])

In [85]:
two_dim_array = np.append(two_dim_array, [[-10, -20, -30]], axis=0)
two_dim_array

array([[ -1,  -2,  -2],
       [  1,   2,   3],
       [  4,   5,   6],
       [ 10,  20,  90],
       [-10, -20, -30]])

In [86]:
two_dim_array = np.delete(two_dim_array, 2, axis=0)
two_dim_array

array([[ -1,  -2,  -2],
       [  1,   2,   3],
       [ 10,  20,  90],
       [-10, -20, -30]])